/**
 * DMS Reference API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Type } from './type';


export interface AggregateFunction { 
    readonly aggregateMethodName?: string | null;
    caption?: string | null;
    sourceField?: string | null;
    functionName?: string | null;
    memberType?: Type;
    resultFormatString?: string | null;
}

