/**
 * DMS Reference API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type CallingConventions = 1 | 2 | 3 | 32 | 64;

export const CallingConventions = {
    NUMBER_1: 1 as CallingConventions,
    NUMBER_2: 2 as CallingConventions,
    NUMBER_3: 3 as CallingConventions,
    NUMBER_32: 32 as CallingConventions,
    NUMBER_64: 64 as CallingConventions
};

