/**
 * DMS Reference API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SortDescriptor } from './sortDescriptor';
import { AggregateDescriptor } from './aggregateDescriptor';
import { GroupDescriptor } from './groupDescriptor';


export interface DataSourceRequest { 
    page?: number;
    pageSize?: number;
    sorts?: Array<SortDescriptor> | null;
    filters?: Array<object> | null;
    groups?: Array<GroupDescriptor> | null;
    aggregates?: Array<AggregateDescriptor> | null;
    groupPaging?: boolean;
    includeSubGroupCount?: boolean;
    skip?: number;
    take?: number;
}

