/**
 * DMS Reference API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type EventAttributes = 0 | 512 | 1024;

export const EventAttributes = {
    NUMBER_0: 0 as EventAttributes,
    NUMBER_512: 512 as EventAttributes,
    NUMBER_1024: 1024 as EventAttributes
};

