/**
 * DMS Reference API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FieldAttributes = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 16 | 32 | 64 | 128 | 256 | 512 | 1024 | 4096 | 8192 | 32768 | 38144;

export const FieldAttributes = {
    NUMBER_0: 0 as FieldAttributes,
    NUMBER_1: 1 as FieldAttributes,
    NUMBER_2: 2 as FieldAttributes,
    NUMBER_3: 3 as FieldAttributes,
    NUMBER_4: 4 as FieldAttributes,
    NUMBER_5: 5 as FieldAttributes,
    NUMBER_6: 6 as FieldAttributes,
    NUMBER_7: 7 as FieldAttributes,
    NUMBER_16: 16 as FieldAttributes,
    NUMBER_32: 32 as FieldAttributes,
    NUMBER_64: 64 as FieldAttributes,
    NUMBER_128: 128 as FieldAttributes,
    NUMBER_256: 256 as FieldAttributes,
    NUMBER_512: 512 as FieldAttributes,
    NUMBER_1024: 1024 as FieldAttributes,
    NUMBER_4096: 4096 as FieldAttributes,
    NUMBER_8192: 8192 as FieldAttributes,
    NUMBER_32768: 32768 as FieldAttributes,
    NUMBER_38144: 38144 as FieldAttributes
};

