/**
 * DMS Reference API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type GenericParameterAttributes = 0 | 1 | 2 | 3 | 4 | 8 | 16 | 28;

export const GenericParameterAttributes = {
    NUMBER_0: 0 as GenericParameterAttributes,
    NUMBER_1: 1 as GenericParameterAttributes,
    NUMBER_2: 2 as GenericParameterAttributes,
    NUMBER_3: 3 as GenericParameterAttributes,
    NUMBER_4: 4 as GenericParameterAttributes,
    NUMBER_8: 8 as GenericParameterAttributes,
    NUMBER_16: 16 as GenericParameterAttributes,
    NUMBER_28: 28 as GenericParameterAttributes
};

