/**
 * DMS Reference API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Type } from './type';
import { ClientHandlerDescriptor } from './clientHandlerDescriptor';
import { AggregateFunction } from './aggregateFunction';
import { ListSortDirection } from './listSortDirection';


export interface GroupDescriptor { 
    member?: string | null;
    sortDirection?: ListSortDirection;
    sortCompare?: ClientHandlerDescriptor;
    memberType?: Type;
    displayContent?: object | null;
    readonly aggregateFunctions?: Array<AggregateFunction> | null;
}

