/**
 * DMS Reference API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type LayoutKind = 0 | 2 | 3;

export const LayoutKind = {
    NUMBER_0: 0 as LayoutKind,
    NUMBER_2: 2 as LayoutKind,
    NUMBER_3: 3 as LayoutKind
};

