/**
 * DMS Reference API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MemberTypes = 1 | 2 | 4 | 8 | 16 | 32 | 64 | 128 | 191;

export const MemberTypes = {
    NUMBER_1: 1 as MemberTypes,
    NUMBER_2: 2 as MemberTypes,
    NUMBER_4: 4 as MemberTypes,
    NUMBER_8: 8 as MemberTypes,
    NUMBER_16: 16 as MemberTypes,
    NUMBER_32: 32 as MemberTypes,
    NUMBER_64: 64 as MemberTypes,
    NUMBER_128: 128 as MemberTypes,
    NUMBER_191: 191 as MemberTypes
};

