/**
 * DMS Reference API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MethodImplAttributes = 0 | 1 | 2 | 3 | 4 | 8 | 16 | 32 | 64 | 128 | 256 | 512 | 4096 | 65535;

export const MethodImplAttributes = {
    NUMBER_0: 0 as MethodImplAttributes,
    NUMBER_1: 1 as MethodImplAttributes,
    NUMBER_2: 2 as MethodImplAttributes,
    NUMBER_3: 3 as MethodImplAttributes,
    NUMBER_4: 4 as MethodImplAttributes,
    NUMBER_8: 8 as MethodImplAttributes,
    NUMBER_16: 16 as MethodImplAttributes,
    NUMBER_32: 32 as MethodImplAttributes,
    NUMBER_64: 64 as MethodImplAttributes,
    NUMBER_128: 128 as MethodImplAttributes,
    NUMBER_256: 256 as MethodImplAttributes,
    NUMBER_512: 512 as MethodImplAttributes,
    NUMBER_4096: 4096 as MethodImplAttributes,
    NUMBER_65535: 65535 as MethodImplAttributes
};

