/**
 * DMS Reference API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MethodAttributes = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 16 | 32 | 64 | 128 | 256 | 512 | 1024 | 2048 | 4096 | 8192 | 16384 | 32768 | 53248;

export const MethodAttributes = {
    NUMBER_0: 0 as MethodAttributes,
    NUMBER_1: 1 as MethodAttributes,
    NUMBER_2: 2 as MethodAttributes,
    NUMBER_3: 3 as MethodAttributes,
    NUMBER_4: 4 as MethodAttributes,
    NUMBER_5: 5 as MethodAttributes,
    NUMBER_6: 6 as MethodAttributes,
    NUMBER_7: 7 as MethodAttributes,
    NUMBER_8: 8 as MethodAttributes,
    NUMBER_16: 16 as MethodAttributes,
    NUMBER_32: 32 as MethodAttributes,
    NUMBER_64: 64 as MethodAttributes,
    NUMBER_128: 128 as MethodAttributes,
    NUMBER_256: 256 as MethodAttributes,
    NUMBER_512: 512 as MethodAttributes,
    NUMBER_1024: 1024 as MethodAttributes,
    NUMBER_2048: 2048 as MethodAttributes,
    NUMBER_4096: 4096 as MethodAttributes,
    NUMBER_8192: 8192 as MethodAttributes,
    NUMBER_16384: 16384 as MethodAttributes,
    NUMBER_32768: 32768 as MethodAttributes,
    NUMBER_53248: 53248 as MethodAttributes
};

