/**
 * DMS Reference API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SecurityRuleSet = 0 | 1 | 2;

export const SecurityRuleSet = {
    NUMBER_0: 0 as SecurityRuleSet,
    NUMBER_1: 1 as SecurityRuleSet,
    NUMBER_2: 2 as SecurityRuleSet
};

