/**
 * DMS Reference API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TypeAttributes = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 16 | 24 | 32 | 128 | 256 | 1024 | 2048 | 4096 | 8192 | 16384 | 65536 | 131072 | 196608 | 262144 | 264192 | 1048576 | 12582912;

export const TypeAttributes = {
    NUMBER_0: 0 as TypeAttributes,
    NUMBER_1: 1 as TypeAttributes,
    NUMBER_2: 2 as TypeAttributes,
    NUMBER_3: 3 as TypeAttributes,
    NUMBER_4: 4 as TypeAttributes,
    NUMBER_5: 5 as TypeAttributes,
    NUMBER_6: 6 as TypeAttributes,
    NUMBER_7: 7 as TypeAttributes,
    NUMBER_8: 8 as TypeAttributes,
    NUMBER_16: 16 as TypeAttributes,
    NUMBER_24: 24 as TypeAttributes,
    NUMBER_32: 32 as TypeAttributes,
    NUMBER_128: 128 as TypeAttributes,
    NUMBER_256: 256 as TypeAttributes,
    NUMBER_1024: 1024 as TypeAttributes,
    NUMBER_2048: 2048 as TypeAttributes,
    NUMBER_4096: 4096 as TypeAttributes,
    NUMBER_8192: 8192 as TypeAttributes,
    NUMBER_16384: 16384 as TypeAttributes,
    NUMBER_65536: 65536 as TypeAttributes,
    NUMBER_131072: 131072 as TypeAttributes,
    NUMBER_196608: 196608 as TypeAttributes,
    NUMBER_262144: 262144 as TypeAttributes,
    NUMBER_264192: 264192 as TypeAttributes,
    NUMBER_1048576: 1048576 as TypeAttributes,
    NUMBER_12582912: 12582912 as TypeAttributes
};

